name: MATLAB Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      # Set up MATLAB deps
      - run: wget -qO- https://ssd.mathworks.com/supportfiles/ci/matlab-deps/v0/install.sh | sudo bash

      # Get mpm
      - run: |
          wget https://www.mathworks.com/mpm/glnxa64/mpm
          chmod +x mpm

      # Get matlab-batch
      - run: |
          wget https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v1/glnxa64/matlab-batch
          chmod +x matlab-batch
          echo "PATH=$PATH:$PWD" >> "$GITHUB_ENV"

      - run: mpm download --release=R2024a --products=MATLAB Simulink --destination="./matlab"

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@source_test
        with:
          source: "./matlab"
          products: "MATLAB Simulink"

      - name: Run command
        uses: matlab-actions/run-command@v2
        env:
          MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_TOKEN }}
        with:
          command: magic(3)
